### ISSUE TITLE
Dexter Eyes do not close

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/GoPiGo3#146]
The `easygopigo3.EasyGoPiGo3.close_eyes()` command only closes one of the eyes, on GoPiGo3 board. I've tried reboots, and firmware re-flashes, and the issue persists.

**Comment by johnisanerd** [comment]
@CleoQc can you take a look at this one?  Maybe we should bring @mattallen37 in on it if it's a lower level issue?

**Comment by mattallen37** [comment]
Is it consistent? Which eye closes (which LED turns off)? Did you try updating the drivers? Which firmware version are you running?

**Comment by CleoQc** [comment]
At first glance it seems to me this is hardware related. The method works fine on my hardware.

**Comment by CleoQc** [comment]
@graykevinb  any update on your side on this?
