### ISSUE TITLE
Up NodeJS to firmware 1.0.0

### ISSUE THREAD

**Issue by CleoQc** [DexterInd/GoPiGo3#172]
@marcellobarile , 
it seems NodeJS got hurt when we moved the firmware number to 1.0.0  
Now it fails the check. 
I know where the firmware number is set, but before I go in and just change it, could you tell me  if there are side effects?

Biggest change in 1.0.0 is that it supports up to 32 bytes per I2C transaction, rather than 16. What are the implications of that on NodeJS?

**Comment by marcellobarile** [comment]
hi @CleoQc,
I'll check it and let you know asap

**Comment by CleoQc** [comment]
thank you for a very quick answer!!! <3

**Comment by CleoQc** [comment]
Never got verified
