### ISSUE TITLE
Is there a way to provide the odometry in the as a function?

### ISSUE THREAD

**Issue by wilianson** [DexterInd/GoPiGo3#192]
Hi, I am trying to test  in Matlab some controllers for Mobile Robots, I am using a sockets communication between Python and Matlab, but there is a problem when I try to compute the odometry in Matlab, I was wondering if it is possible to me modify the source code in order to make the odometry and provide the position of the robot in centimeters o meters, and its orientation, What steps Should I follow?.
Thanks

**Comment by slowrunner** [comment]
The GoPiGo3 does not maintain a position estimate, nor an orientation estimate for an external processor to interface with.  

The request should not be considered an "issue" with the GoPiGo3 implementation.  

Suggest closing the issue.  Requester can pursue such questions in the support forum https://forum.dexterindustries.com/

**Comment by RobertLucian** [comment]
I have to agree with that. Closing this down.
