### ISSUE TITLE
Error translating line follower Bloxter Code to Python 

### ISSUE THREAD

**Issue by Auroric** [DexterInd/GoPiGo3#251]
When using the line follower blocks, "line follower (red) sees" and "line follower (black) sees", the equivalent python code has a syntax error, causing the code to fail to run. If instead one checks if the line position is equal to a string using the "line_follower values" and the equals and text blocks, the issue is not found. I believe this occurs because, when using the "line follower (red) sees" and "line follower (black) sees" code blocks, the colon that ends the if statement is on the next line.  I have included images of both functioning bloxter code and non-functioning code (where the python equivalents are almost identical, except the colon as noted previously). 

![bloxter_bloxter_error](https://user-images.githubusercontent.com/8205005/60912374-0c51c880-a23a-11e9-9618-43f5c3b9fb7d.PNG)

![bloxter_bloxter_functioning](https://user-images.githubusercontent.com/8205005/60912365-0825ab00-a23a-11e9-8e3a-a2873cf59875.PNG)

![bloxter_python_error](https://user-images.githubusercontent.com/8205005/60912385-0fe54f80-a23a-11e9-889a-675bbba6c5a5.PNG)

**Comment by CleoQc** [comment]
@Auroric 
You are indeed right. Thanks for reporting the issue and debugging it for us. Fix is incoming.

**Comment by CleoQc** [comment]
There is an update for DexterOS available now:
https://www.dexterindustries.com/dexteros/update-dexteros/

(it took a while to post cause we experienced a website issue, the update itself was done pretty quickly)
