### ISSUE TITLE
test_heavy_mutex_2.py  TabError: inconsistent use of tabs and spaces 

### ISSUE THREAD

**Issue by slowrunner** [DexterInd/GoPiGo3#270]
[test_heavy_mutex_2.py](https://github.com/DexterInd/GoPiGo3/blob/master/Software/Python/tests/test_heavy_mutex_2.py) has an errant tab:
```
pi@Carl:~/Dexter/GoPiGo3/Software/Python/tests $ python3 test_heavy_mutex_2.py 
  File "test_heavy_mutex_2.py", line 20
    mutex.release()
                  ^
TabError: inconsistent use of tabs and spaces in indentation
```

Note: Sorry, I have not learned how to do pull request.  This one is really trivial to fix, I should have done it.

**Comment by slowrunner** [comment]
Same error in both [test_distance_sensor.py](https://github.com/DexterInd/GoPiGo3/blob/master/Software/Python/tests/test_distance_sensor.py) and [test_distance_sensor_2.py](https://github.com/DexterInd/GoPiGo3/blob/master/Software/Python/tests/test_distance_sensor_2.py)

**Comment by CleoQc** [comment]
Done, thanks for reporting it!
