### ISSUE TITLE
Addition of easy_light_color_sensor import to easygopigo3.py gives import error 

### ISSUE THREAD

**Issue by slowrunner** [DexterInd/GoPiGo3#281]
The addition of importing easy_light_color_sensor to easygopigo3.py causes an import error:

easy_light_color_sensor.py:198  Invalid Syntax

on Raspbian For Robots Stretch which uses Python 3.5.

The easy_light_color_sensor.py calibrate function uses f-strings which are only supported in Python 3.6 and beyond.

Issue filed against that file:
https://github.com/DexterInd/DI_Sensors/issues/89

**Comment by CleoQc** [comment]
Fixed with https://github.com/DexterInd/DI_Sensors/pull/90
Thanks for bringing this to my attention.
