### ISSUE TITLE
Change link to GoPiGo.io?

### ISSUE THREAD

**Issue by jharris1993** [DexterInd/GoPiGo3#304]
Do you want to change the link to gopigo.io?

Actually, I like the old link, but it might not be consistent with the mandates from The Borg's marketing gods. (wink!)

**Comment by slowrunner** [comment]
Suggest edit issue with which "the link" specifically.  ([The Repository](https://github.com/DexterInd/GoPiGo3) "About"?)

**Comment by CleoQc** [comment]
fixed
