### ISSUE TITLE
WIBNI: Installation Success Test at end of update_gopigo3.sh

### ISSUE THREAD

**Issue by slowrunner** [DexterInd/GoPiGo3#307]
With so many people trying to install GoPiGo3 software on every new release of every variety of OS they see, it "would be nice if" there was a success test at the end of 

update_gopigo3.sh

```
...
installresult=$(python3 -c "import gopigo3" 2>&1)
if [[ $installresult == *"ModuleNotFoundError"* ]]; then
   echo "GOPIGO3 SOFTWARE INSTALLATION FAILURE: "+$installresult
   echo "Suggest installing over Legacy Pi OS"
fi 
```

For reference - Attempting to install over the recently released 64-bit PiOS (2022-01-28) would trigger this warning

**Comment by CleoQc** [comment]
https://github.com/DexterInd/GoPiGo3/pull/315

Thank you!
