### ISSUE TITLE
C++ GoPiGo3 API needs 16tick board support

### ISSUE THREAD

**Issue by slowrunner** [DexterInd/GoPiGo3#324]
The C++ GoPiGo3 API does not support GoPiGo3 robots that have 16 tick encoders.

Additionally:
- The GoPiGo3 instance variables associated with the gpg3_config.json file are not declared and initialized
- An example driving the GoPiGo3 via keyboard control would be helpful

Created pull request https://github.com/DexterInd/GoPiGo3/pull/325 for this issue

**Comment by CleoQc** [comment]
Thank you so much for the PR.
