### ISSUE TITLE
GoPiGo3 C++ API does not fully implement motor tick value.   Additional C++ API examples desired.

### ISSUE THREAD

**Issue by slowrunner** [DexterInd/GoPiGo3#332]
The December 2022 update to the GoPiGo3 C++ API implemented searching and using the 16-tick serial pkl file when creating the /home/pi/Dexter/gpg3_config.json file, but did not make modifications to the set_motor_ and get_motor_ methods to use the ENCODER_TICKS_PER_REVOLUTION and the resulting MOTOR_TICKS_PER_DEGREE.

**Comment by CleoQc** [comment]
Is that answered with your PR #333 ?

**Comment by slowrunner** [comment]
Yes, I'll close it
