### ISSUE TITLE
Firmware update does not work on Stock Raspbian

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/GoPiGo3#49]
I tried updating the firmware of my GoPiGo3 on Raspbian Jessie and got this error:
`pi@raspberrypi:~/GoPiGo3/Firmware $ sudo bash gopigo3_flash_firmware.sh
Updating the GoPiGo3 Firmware with '/home/pi/GoPiGo3/Firmware/GoPiGo3_Firmware_0.3.2.bin'.
sudo: openocd: command not found`

I also looked at the scripts in the openocd folder and they refer to the `Dexter/` folder which obviously doesn't exist on raspbain.

**Comment by CleoQc** [comment]
although I haven't attempted to update the firmware that way, I have installed everything onto latest Jessie (with Pixel) through this call
`curl https://raw.githubusercontent.com/DexterInd/Raspbian_For_Robots/master/upd_script/fetch_gopigo3.sh | bash`
worked great for me. It creates the Dexter folder for you and everything.
