### ISSUE TITLE
No module named mock_package

### ISSUE THREAD

**Issue by angelarw** [DexterInd/GoPiGo3#64]
the latest commit is causing the easygopigo3 to not work. 
"  File "build/bdist.linux-armv7l/egg/easygopigo3.py", line 2251, in <module>
ImportError: No module named mock_package"

this line here: references "mock_package" which is not defined elsewhere
https://github.com/DexterInd/GoPiGo3/blame/master/Software/Python/easygopigo3.py#L2251

**Comment by DexterInd** [comment]
Thanks for the alert here @angelarw we will look at it immediately!

**Comment by RobertLucian** [comment]
@angelarw it's now working.

**Comment by guuskoning** [comment]
Ok, but what should I do now? I've updated the Gopigo 3 firmware but that didn't help.

**Comment by CleoQc** [comment]
Did you update the GoPiGo3 library on your pi?

**Comment by guuskoning** [comment]
Yes, I've followed the tutorials but when I launch the Scracth program I don't get the message "Remote sensor connections enabled". I don't get any errors but the program doesn't work.

**Comment by CleoQc** [comment]
For now, Scratch will only work if you have Raspbian for Robots. Is that the case with your setup?

**Comment by guuskoning** [comment]
Yes, I have Raspbian for Robots
